# Serve the portfolio website for tanujsharma.me
# Located at /var/www/portfolio

http {
   server {
      listen 80;
      server_name tanujsharma.me;

      root /var/www/portfolio;
      index index.html;

      location / {
         # Example if the request is tanujsharma.me/about
         #  nginx will look for the file /var/www/portfolio/about
         #  If the file is not found, it will look for the folder /var/www/portfolio/about
         #  If the folder is not found, it will serve the file /var/www/portfolio/index.html (Good for Single Page Applications)

         try_files $uri $uri/ /index.html;
      }
   }
}